apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-kevx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-kevx
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-kevx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-kevx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-kevx
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/happy-path-tenant/appstudio/dc-metro-map-kevx@sha256:79183e02f024ddafc5c2279e83a0397d0aa59a001d1a5081323ae3043c74a32c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
